matrix:
  include:
    - language: java
      jdk: oraclejdk8
      env:
          - TEAM=ttt_1
      before_script: cd java/ttt_1

    - language: java
      jdk: oraclejdk8
      env:
          - TEAM=ttt_2
      before_script: cd java/ttt_2

    - language: java
      jdk: oraclejdk8
      env:
          - TEAM=ttt_3
      before_script: cd java/ttt_3
